StatTrackr.Web/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StatTrackr.Web.Models;
using StatTrackr.Framework.Domain;
using StatTrackr.Framework;

namespace StatTrackr.Web.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class PlayerController : Controller
    {
        //
        // GET: /Player/
        StatContext ctx = new StatContext();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View(new PlayerModel());
        }



        [HttpPost]
        public ActionResult Create(PlayerModel player)
        {
            if (ModelState.IsValid)
            {
                ctx.Players.Add(player);
                ctx.SaveChanges();
            }
           
           
            return RedirectToAction("Index","Team", new{id=player.CurrentTeamId});
        }
    }
}

StatTrackr.Web/Views/Shared/AddTeamToLeague.cshtml
@model StatTrackr.Web.Models.TeamLeagueModel
<style>
	.demo ul { list-style-type: none; margin: 0; padding: 0; margin-bottom: 10px; }
	.demo li { margin: 5px; padding: 5px; width: 150px; }
	</style>
	<script type="text/javascript">
	
        
	    $(function () {
	        $('#dialog').dialog({
	            autoopen: false,
	            width: 600,
	            resizable: false,
	            title: 'Add/Remove Teams',
	            url: "",
	            modal: true,
	            buttons: {
	                "Save": function () {

	                    $.ajax({
	                        url: '/Team/Add',
	                        type: 'POST',
	                        traditional: true,
	                        data: { "addIds": getArray("#sortable1"), "removeIds": getArray("#sortable2"), "leagueid": "@ViewBag.LeagueID" },
	                        success: function () {
	                            if ($("#dialog form").length > 0) {
	                                $("#dialog form").submit();

	                            } else {
	                                alert("Success");
	                                window.location.reload();

	                            }
	                        }
	                    });

	                },
	                "Cancel": function () {
	                    $(this).dialog("close");
	                }
	            }
	        });


	    });
	    $(function () {
	        $("#sortable1, #sortable2").sortable({
	            connectWith: ".connectedSortable",
	            stop: function (event, ui) {

	            }
	        }).disableSelection();
	    });


	    function getArray(div) {
	        var list = [];
	        $(div).find("li").each(function () {
	            list.push($(this).attr("rel"));

	        });
	        return list;
	    }
	</script>



<div class="relationships">

@*Current Items*@
<div class="rel-list">
    <h4>Current Items</h4>
<ul id="sortable1"  class="connectedSortable">
@foreach (var item in Model.CurrentTeams)
{
    <li id="@item" rel="@item.TeamID" class="ui-state-default">
        <div class="editor button editmodal" rel="/Team/Edit/@item.TeamID">Edit</div><span title="@item.TeamName">@item.TeamName</span>
    <div class="clear"></div>
    </li>
}
	
</ul>
</div>
	@*Master list*@
    <div class="rel-list">
    <h4>All Items</h4>
<ul id="sortable2"  class="connectedSortable">
@foreach (var master in Model.AvailableTeams.OrderBy(x => x.TeamName))
{
    <li rel="@master.TeamID" class="ui-state-default">
        <div class="editor button editmodal" rel="/Team/Edit/@master.TeamID">Edit</div><span title="@master.TeamName">@master.TeamName</span>
    <div class="clear"></div>
    </li>
}
	

</ul>
</div>
<div class="clear"></div>
</div>

StatTrackr.Web/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en-us">
    <head>
	    <meta http-equiv="X-UA-Compatible" content="IE=Edge;chrome=1" />

        <link rel="apple-touch-con" href="" />

        <title>@ViewBag.Title</title>

        <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0" />

	    <!-- The Columnal Grid and mobile stylesheet -->
	    <link rel="stylesheet" href="@Url.Content("~/content/styles/columnal/columnal.css")" type="text/css" media="screen" />

	    <!-- Fixes for IE -->
	    <!--[if lt IE 9]>
                <link rel="stylesheet" href="@Url.Content("~/content/styles/columnal/ie.css")" type="text/css" media="screen" />
                <link rel="stylesheet" href="@Url.Content("~/content/styles/columnal/ie8.css")" type="text/css" media="screen" />
                <script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"></script>
	    <![endif]-->        
        
	
	    <!-- Now that all the grids are loaded, we can move on to the actual styles. --> 
        <link rel="stylesheet" href="@Url.Content("~/content/scripts/jqueryui/jqueryui.css")" type="text/css" media="screen" />
        <link rel="stylesheet" href="@Url.Content("~/content/styles/style.css")" type="text/css" media="screen" />
        <link rel="stylesheet" href="@Url.Content("~/content/styles/global.css")" type="text/css" media="screen" />
        <link rel="stylesheet" href="@Url.Content("~/content/styles/config.css")" type="text/css" media="screen" />
        
        <!-- Adds HTML5 Placeholder attributes to those lesser browsers (i.e. IE) -->
        <script type="text/javascript" src="@Url.Content("~/content/scripts/jquery.placeholder.1.2.min.shrink.js")"></script>

        <!-- Use CDN on production server -->
        <script type="text/javascript" src="@Url.Content("~/Content/scripts/jquery-1.6.4.min.js")"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
        
        <!-- Menu -->
        <link rel="stylesheet" href="@Url.Content("~/content/scripts/superfish/superfish.css")" type="text/css" media="screen" />
        <script src="@Url.Content("~/content/scripts/superfish/superfish.js")" type="text/javascript"></script>
		
        <!-- Js used in the theme -->
        <script src="@Url.Content("~/content/scripts/muse.js")" type="text/javascript"></script>

    </head>
    <body>
        <div id="wrap">
	        <div id="main">
                <header class="container">
                    <div class="row clearfix">
                        <div class="left">
                            <a href="index.html" id="logo">Muse</a>
                        </div>
                        <div class="right">
                            <ul id="toolbar">
                                <li><span>Logged in as</span>
                                    <a class="user" href="/admin">@StatTrackr.Framework.Security.CodeFirstSecurity.CurrentUserName</a>
                                    <a id="loginarrow" href="javascript:void(0);"></a>
                                </li>
                                <li><a id="messages" href="#">Messages</a></li>
                                <li><a id="settings" href="#">Settings</a></li>
                                <li><a id="search" href="#">Search</a></li>
                            </ul>
                            <div id="logindrop">
                                <ul>
                                    <li id="editprofile"><a href="/account/edit">Edit Profile</a></li>
                                    <li id="logoutprofile"><a href="/account/logoff">Logout</a></li>
                                </ul>
                            </div>
                            <div id="searchdrop">
                                <input type="text" id="searchbox" placeholder="Search...">
                            </div>
                        </div>  
                    </div>
                </header>
                <nav class="container">
                    <select class="mobile-only row clearfix" onchange="window.open(this.options[this.selectedIndex].value,'_top')">
                            <option value="index.html">Stat Tracker</option>
                    </select>

                    <ul class="sf-menu mobile-hide row clearfix">
                        <li @MvcHtmlHelpers.HTMLHelpers.SelectedNavItem(this.Html, ViewBag.selectedPage, "")><a href="/"><span>Home</span></a></li>
                        
                        <li @MvcHtmlHelpers.HTMLHelpers.SelectedNavItem(this.Html, ViewBag.selectedPage, "league")>
                            <a href="/league/"><span>Leagues</span></a>
                            @MvcHtmlHelpers.HTMLHelpers.RenderNavigationDropdown(this.Html, ViewBag.NavigationItems, "leagues")
                        </li>
                        
                        <li @MvcHtmlHelpers.HTMLHelpers.SelectedNavItem(this.Html, ViewBag.selectedPage, "division")>
                            <a href="/division/"><span>Divisions</span></a>
                            @MvcHtmlHelpers.HTMLHelpers.RenderNavigationDropdown(this.Html, ViewBag.NavigationItems, "divisions")
                        </li>
                        
                        <li @MvcHtmlHelpers.HTMLHelpers.SelectedNavItem(this.Html, ViewBag.selectedPage, "team")>
                            <a href="/team/"><span>Teams</span></a>
                            @MvcHtmlHelpers.HTMLHelpers.RenderNavigationDropdown(this.Html, ViewBag.NavigationItems, "teams")
                        </li>
                        
                        <li @MvcHtmlHelpers.HTMLHelpers.SelectedNavItem(this.Html, ViewBag.selectedPage, "players")><a href="/players"><span>Players</span></a></li>
                        <li @MvcHtmlHelpers.HTMLHelpers.SelectedNavItem(this.Html, ViewBag.selectedPage, "stats")><a href="/stats"><span>Stats</span></a></li>
                        <li @MvcHtmlHelpers.HTMLHelpers.SelectedNavItem(this.Html, ViewBag.selectedPage, "games")><a href="/games"><span>Games</span></a></li>
                    </ul>
                </nav>
                <div id="titlediv">
                    <div class="clearfix container" id="pattern">
                        <div class="row">
                            <div class="col_12">
                                <h1>Stat Tracker</h1>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="container" id="actualbody">
                    @RenderBody()
                </div>
            </div>
        </div>
        <footer>
            <div class="container">
		        <div class="row clearfix">
			        <div class="col_12">
				        <span class="left">&copy; 2011 44 Lights.</span>
				        <span class="right">Powered by Drosticon</span>
			        </div>
		        </div>
            </div>
        </footer>
    </body>
</html>

StatTrackr.Web/Views/Shared/_DivisionCreatePartial.cshtml
@model StatTrackr.Web.Models.DivisionModel

<script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>DivisionModel</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

StatTrackr.Web/Views/Shared/_EditLeague.cshtml
@model StatTrackr.Web.Models.LeagueModel


@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>League</legend>

        @Html.HiddenFor(model => model.LeagueID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        <div class="editor-label">
           Division
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.DivisionID, new SelectList(StatTrackr.Web.Models.StatHelper.GetAllDivisions(),"DivisionID", "Name"), "-----Division----")
            @Html.ValidationMessageFor(model => model.Name)
        </div>
    </fieldset>
}

StatTrackr.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-us">
    <head>
	    <meta http-equiv="X-UA-Compatible" content="IE=Edge;chrome=1" />

        <link rel="apple-touch-con" href="" />

        <title>@ViewBag.Title</title>

        <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0" />

	    <!-- The Columnal Grid and mobile stylesheet -->
	    <link rel="stylesheet" href="@Url.Content("~/content/styles/columnal/columnal.css")" type="text/css" media="screen" />

	    <!-- Fixes for IE -->
	    <!--[if lt IE 9]>
                <link rel="stylesheet" href="@Url.Content("~/content/styles/columnal/ie.css")" type="text/css" media="screen" />
                <link rel="stylesheet" href="@Url.Content("~/content/styles/columnal/ie8.css")" type="text/css" media="screen" />
                <script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"></script>
	    <![endif]-->        
        
	
	    <!-- Now that all the grids are loaded, we can move on to the actual styles. --> 
        <link rel="stylesheet" href="@Url.Content("~/content/scripts/jqueryui/jqueryui.css")" type="text/css" media="screen" />
        <link rel="stylesheet" href="@Url.Content("~/content/styles/style.css")" type="text/css" media="screen" />
        <link rel="stylesheet" href="@Url.Content("~/content/styles/global.css")" type="text/css" media="screen" />
        <link rel="stylesheet" href="@Url.Content("~/content/styles/config.css")" type="text/css" media="screen" />
        
        <!-- Adds HTML5 Placeholder attributes to those lesser browsers (i.e. IE) -->
        <script type="text/javascript" src="@Url.Content("~/content/scripts/jquery.placeholder.1.2.min.shrink.js")"></script>

        <!-- Use CDN on production server -->
        <script type="text/javascript" src="@Url.Content("~/Content/scripts/jquery-1.6.4.min.js")"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
        
        <!-- Menu -->
        <link rel="stylesheet" href="@Url.Content("~/content/scripts/superfish/superfish.css")" type="text/css" media="screen" />
        <script src="@Url.Content("~/content/scripts/superfish/superfish.js")" type="text/javascript"></script>
		
        <!-- Js used in the theme -->
        <script src="@Url.Content("~/content/scripts/muse.js")" type="text/javascript"></script>

    </head>
    <body>
        <div id="wrap">
	        <div id="main">
                <header class="container">
                    <div class="row clearfix">
                        <div class="left">
                            <a href="index.html" id="logo">Muse</a>
                        </div>
                        <div class="right">
                            <ul id="toolbar">
                                @if (StatTrackr.Framework.Security.CodeFirstSecurity.IsAuthenticated)
                                {
                                    <li><span>Logged in as</span>
                                        <a class="user" href="/admin">@StatTrackr.Framework.Security.CodeFirstSecurity.CurrentUserName</a>
                                        <a id="loginarrow" href="javascript:void(0);"></a>
                                    </li>
                                    <li><a id="messages" href="#">Messages</a></li>
                                    <li><a id="settings" href="#">Settings</a></li>
                                    <li><a id="search" href="#">Search</a></li>
                                }
                                else
                                {
                                    // html for logging in
                                    <li>
                                        <a id="login" href="/account/logon">Login</a>
                                    </li>
                                }
                            </ul>
                            <div id="logindrop">
                                <ul>
                                    <li id="editprofile"><a href="/account/edit">Edit Profile</a></li>
                                    <li id="logoutprofile"><a href="/account/logoff">Logout</a></li>
                                </ul>
                            </div>
                            <div id="searchdrop">
                                <input type="text" id="searchbox" placeholder="Search...">
                            </div>
                        </div>  
                    </div>
                </header>
                <nav class="container">
                    <select class="mobile-only row clearfix" onchange="window.open(this.options[this.selectedIndex].value,'_top')">
                            <option value="index.html">Stat Tracker</option>
                    </select>

                    <ul class="sf-menu mobile-hide row clearfix">
                        <li @MvcHtmlHelpers.HTMLHelpers.SelectedNavItem(this.Html, ViewBag.selectedPage, "home")><a href="/"><span>Home</span></a></li>
                        <li @MvcHtmlHelpers.HTMLHelpers.SelectedNavItem(this.Html, ViewBag.selectedPage, "about")><a href="/home/about"><span>About Us</span></a></li>
                        <li @MvcHtmlHelpers.HTMLHelpers.SelectedNavItem(this.Html, ViewBag.selectedPage, "features")><a href="/home/features"><span>Features</span></a></li>
                        <li @MvcHtmlHelpers.HTMLHelpers.SelectedNavItem(this.Html, ViewBag.selectedPage, "apps")><a href="/home/apps"><span>Apps</span></a></li>
                        <li @MvcHtmlHelpers.HTMLHelpers.SelectedNavItem(this.Html, ViewBag.selectedPage, "contact")><a href="/home/contact"><span>Contact Us</span></a></li>
                    </ul>
                </nav>
                <div id="titlediv">
                    <div class="clearfix container" id="pattern">
                        <div class="row">
                            <div class="col_12">
                                <h1>Stat Tracker</h1>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="container" id="actualbody">
                    @RenderBody()
                </div>
            </div>
        </div>
        <footer>
            <div class="container">
		        <div class="row clearfix">
			        <div class="col_12">
				        <span class="left">&copy; 2011 44 Lights.</span>
				        <span class="right">Powered by Drosticon</span>
			        </div>
		        </div>
            </div>
        </footer>
    </body>
</html>

StatTrackr.Web/Views/Shared/_LeagueCreatePartial.cshtml
@model StatTrackr.Web.Models.LeagueModel

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)  
        <div class="editor-label">
            @Html.LabelFor(model => model.name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.name)
            @Html.ValidationMessageFor(model => model.name)
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
}

StatTrackr.Web/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}

StatTrackr.Web/Views/Shared/_LoginLayout.cshtml
<!doctype html>  
<html lang="en-us">

<head>
	<meta http-equiv="X-UA-Compatible" content="IE=Edge;chrome=1" >
	<meta charset="utf-8">
	<title>Muse Admin Panel | Login</title>

	<meta name="viewport" content="width=device-width, initial-scale=1.0"> 

	<!-- The Columnal Grid and mobile stylesheet -->
	<link rel="stylesheet" href="@Url.Content("~/content/styles/columnal/columnal.css")" type="text/css" media="screen" />

	<!-- Fixes for IE -->
	<!--[if lt IE 9]>
            <link rel="stylesheet" href="assets/styles/columnal/ie.css" type="text/css" media="screen" />
            <link rel="stylesheet" href="assets/styles/ie8.css" type="text/css" media="screen" />
            <script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"></script>
	<![endif]-->

	<!-- Now that all the grids are loaded, we can move on to the actual styles. --> 
    <link rel="stylesheet" href="@Url.Content("~/content/scripts/jqueryui/jqueryui.css")" type="text/css" media="screen" />
    <link rel="stylesheet" href="@Url.Content("~/content/styles/style.css")" type="text/css" media="screen" />
    <link rel="stylesheet" href="@Url.Content("~/content/styles/global.css")" type="text/css" media="screen" />
    <link rel="stylesheet" href="@Url.Content("~/content/styles/config.css")" type="text/css" media="screen" />
              
</head>
<body id="login">
    <div class="container">
        <div class="row">
            <a href="login.php" class="center block"><img src="assets/images/biglogo.png" /></a>
            @RenderBody()
        </div>
    </div>
</body>
</html>

StatTrackr.Web/Views/Shared/_PlayerCreatePartial.cshtml
@model StatTrackr.Web.Models.PlayerModel

<script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Create", "Player")) {
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.CurrentTeamId)
        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Number)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Number)
            @Html.ValidationMessageFor(model => model.Number)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Experiance)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Experiance)
            @Html.ValidationMessageFor(model => model.Experiance)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Position)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Position)
            @Html.ValidationMessageFor(model => model.Position)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Weight)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Weight)
            @Html.ValidationMessageFor(model => model.Weight)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Height)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Height)
            @Html.ValidationMessageFor(model => model.Height)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TwitterHandle)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TwitterHandle)
            @Html.ValidationMessageFor(model => model.TwitterHandle)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>

}

StatTrackr.Web/Views/Shared/_TeamCreatePartial.cshtml
@model StatTrackr.Web.Models.TeamModel

<script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<h2>Create</h2>
@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
        <div class="editor-label">
            @Html.LabelFor(model => model.TeamName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TeamName)
            @Html.ValidationMessageFor(model => model.TeamName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PhotoUrl)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PhotoUrl)
            @Html.ValidationMessageFor(model => model.PhotoUrl)
        </div>
         <div class="editor-field">
         @if (Model.League == null)
         {
            @Html.DropDownListFor(model => model.LeagueId, new SelectList(StatTrackr.Web.Models.StatHelper.GetAllLeagues(),"Name", "LeagueID"), "----- Select League-----")
         }
            <a href="javascript:void(0);" rel="/League/Create">Create New League</a>
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
}